### ISSUE TITLE
USPS calculators erroneously returning nil due to mismatched service names

### ISSUE THREAD

**Issue by dpritchett** [spree-contrib/spree_active_shipping#133]
Here's a quote sheet from the USPS api as of this morning for a domestic shipment:

``` ruby
{"USPS First-Class Mail Postcards"=>33,
 "USPS First-Class Mail Large Postcards"=>46,
 "USPS First-Class Mail Letter"=>86,
 "USPS First-Class Mail Parcel"=>207,
 "USPS Library Mail"=>240,
 "USPS Media Mail"=>253,
 "USPS Priority Mail 1-Day Gift Card Flat Rate Envelope"=>560,
 "USPS Priority Mail 1-Day Window Flat Rate Envelope"=>560,
 "USPS Priority Mail 1-Day Small Flat Rate Envelope"=>560,
 "USPS Standard Post"=>560,
 "USPS Priority Mail 1-Day Flat Rate Envelope"=>560,
 "USPS Priority Mail 1-Day"=>560,
 "USPS Priority Mail 1-Day Legal Flat Rate Envelope"=>575,
 "USPS Priority Mail 1-Day Small Flat Rate Box"=>580,
 "USPS Priority Mail 1-Day Padded Flat Rate Envelope"=>595,
 "USPS Priority Mail 1-Day Medium Flat Rate Box"=>1235,
 "USPS Priority Mail Express 2-Day Hold For Pickup"=>1410,
 "USPS Priority Mail Express 2-Day"=>1410,
 "USPS Priority Mail 1-Day Large Flat Rate Box"=>1685,
 "USPS Priority Mail Express 2-Day Flat Rate Envelope Hold For Pickup"=>1995,
 "USPS Priority Mail Express 2-Day Padded Flat Rate Envelope Hold For Pickup"=>
  1995,
 "USPS Priority Mail Express 2-Day Legal Flat Rate Envelope Hold For Pickup"=>
  1995,
 "USPS Priority Mail Express 2-Day Padded Flat Rate Envelope"=>1995,
 "USPS Priority Mail Express 2-Day Legal Flat Rate Envelope"=>1995,
 "USPS Priority Mail Express 2-Day Flat Rate Envelope"=>1995,
 "USPS Priority Mail Express 2-Day Flat Rate Boxes"=>3995,
 "USPS Priority Mail Express 2-Day Flat Rate Boxes Hold For Pickup"=>3995}
```

Here's the current name mapping for the USPS rate offerings from `en.yml`:

``` yaml
  usps:
    express_mail: "USPS Express Mail"
    express_mail_intl: "USPS Express Mail International"
    media_mail: "USPS Media Mail"
    priority_mail: "USPS Priority Mail"
    priority_mail_small_flat_rate_box: "USPS Priority Mail Small Flat Rate Box"
    priority_mail_medium_flat_rate_box: "USPS Priority Mail Medium Flat Rate Box"
    priority_mail_large_flat_rate_box: "USPS Priority Mail Large Flat Rate Box"
    priority_mail_flat_rate_envelope: "USPS Priority Mail Flat Rate Envelope"
    priority_mail_international: "USPS Priority Mail International"
    priority_mail_international_small_flat_rate_box: "USPS Priority Mail International Small Flat Rate Box"
    priority_mail_international_medium_flat_rate_box: "USPS Priority Mail International Medium Flat Rate Box"
    priority_mail_international_large_flat_rate_box: "USPS Priority Mail International Large Flat Rate Box"
```

Since the [base calculator resolves the API responses by comparing the response hash key to the calculator's localized :description](https://github.com/spree/spree_active_shipping/blob/a3e67701eda4908fdb8a4c0cfd47544489c0f822/app/models/spree/calculator/shipping/active_shipping/base.rb#L51), this is a problem.  Not sure if there's a way around manually updating the YAML file when the API udpates, but here we are.

Thanks!
